services:
  source:
    platform: linux/amd64
    build:
      context: docker
    environment:
      SERVER_ID: "1"
    ports:
      - 13306:3306
  replica:
    platform: linux/amd64
    build:
      context: docker
    environment:
      SERVER_ID: "2"
    ports:
      - 13307:3306
